interface userTypesProp {
    SET_USER_DATA: string,
    FETCH_USER_DATA:string
}

export const userTypes = {
    SET_USER_DATA: 'SET_USER_DATA',
    FETCH_USER_DATA:'FETCH_USER_DATA',
    SET_USER_SUCCESS:'SET_USER_SUCCESS',
    FETCH_USER_ERROR:'FETCH_USER_ERROR',
    SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
    FETCH_ACCESS_TOKEN:'FETCH_ACCESS_TOKEN',
    SEARCH_FOR_USER: 'SEARCH_FOR_USER',
    
}