export const clangroupTypes = {
    CREATE_NEW_GROUP:'CREATE_NEW_GROUP',
    NEW_GROUP_ERROR:'NEW_GROUP_ERROR',
    FETCH_ALL_GROUPS:'FETCH_ALL_GROUPS',
    FETCH_ALL_GROUPS_ERROR:'FETCH_ALL_GROUPS_ERROR',
    CHANGE_CLAN_TAB_ID: 'CHANGE_CLAN_TAB_ID',
    FETCH_GROUP_BY_ID: 'FETCH_GROUP_BY_ID',
    FETCH_GROUP_BY_ID_ERROR: 'FETCH_GROUP_BY_ID_ERROR'
}

