export const featureTypes = {
    SET_ACTIVE_SIDEBAR:'SET_ACTIVE_SIDEBAR',
    SET_ACTIVE_USER_SIDEMENU:'SET_ACTIVE_USER_SIDEMENU',
    SET_SCREEN_SIZE:'SET_SCREEN_SIZE',
    OPEN_EDIT_MODAL:'OPEN_EDIT_MODAL'
}

